blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/erkerkan/clickhouse-ui/discussions
    about: For open-ended questions, ideas and show-and-tell.
